language: swift
os:
    - linux
    - osx
sudo: required
dist: trusty
osx_image: xcode9.3
branches:
    only:
        - master
        - develop
env:
    global:
        - SWIFT_VERSION=swift-4.1
    matrix:
        - DESTINATION="OS=4.3,name=Apple Watch - 42mm"  RUN_TESTS="NO"  POD_LINT="NO"
        - DESTINATION="OS=3.2,name=Apple Watch - 42mm"  RUN_TESTS="NO"  POD_LINT="NO"
        - DESTINATION="OS=2.2,name=Apple Watch - 42mm"  RUN_TESTS="NO"  POD_LINT="NO"

        - DESTINATION="OS=11.3,name=iPhone X"         RUN_TESTS="YES"  BUILD_EXAMPLE="YES"  POD_LINT="YES"
        - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"  RUN_TESTS="YES"  BUILD_EXAMPLE="YES"  POD_LINT="NO"
        - DESTINATION="OS=9.3,name=iPhone 6"          RUN_TESTS="YES"  BUILD_EXAMPLE="YES"  POD_LINT="NO"

        - DESTINATION="OS=11.3,name=Apple TV 4K"     RUN_TESTS="YES"  POD_LINT="NO"
        - DESTINATION="OS=10.2,name=Apple TV 1080p"  RUN_TESTS="YES"  POD_LINT="NO"
        - DESTINATION="OS=9.2,name=Apple TV 1080p"   RUN_TESTS="YES"  POD_LINT="NO"

        - DESTINATION="arch=x86_64"  RUN_TESTS="YES"  POD_LINT="NO"
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        eval "$(curl -sL https://swiftenv.fuller.li/install.sh)";
    else
        gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet;
    fi
script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        ./.travis/build/linux.sh
    else
        ./travis/build/macos.sh
    fi
