sudo: required
dist: trusty
language: generic
osx_image: xcode9.3

# Dependencies
before_install: chmod +x ./.travis/deps.sh
install: ./.travis/deps.sh

# Build Script
before_script: chmod +x ./.travis/build.sh
script: ./.travis/build.sh

# Update Code Coverage
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash <(curl -s https://codecov.io/bash) fi

# Build Matrix
matrix:
  include:
    # Linux
    - os: linux
      env: SWIFT_VERSION=swift-4.1

    # macOS
    - os: osx
      env: DESTINATION="arch=x86_64"  SCHEME="CELLULAR macOS" RUN_TESTS="YES"  POD_LINT="NO"

    # iOS
    - os: osx
      env: DESTINATION="OS=11.3,name=iPhone X"        SCHEME="CELLULAR iOS" RUN_TESTS="YES" POD_LINT="YES"
    - os: osx
      env: DESTINATION="OS=10.3.1,name=iPhone 7 Plus" SCHEME="CELLULAR iOS" RUN_TESTS="YES" POD_LINT="NO"
    - os: osx
      env: DESTINATION="OS=9.3,name=iPhone 6"         SCHEME="CELLULAR iOS" RUN_TESTS="YES" POD_LINT="NO"
    # watchOS
    - os: osx
      env: DESTINATION="OS=4.3,name=Apple Watch - 42mm" SCHEME="CELLULAR watchOS" RUN_TESTS="NO" POD_LINT="NO"
    - os: osx
      env: DESTINATION="OS=3.2,name=Apple Watch - 42mm" SCHEME="CELLULAR watchOS" RUN_TESTS="NO" POD_LINT="NO"
    - os: osx
      env: DESTINATION="OS=2.2,name=Apple Watch - 42mm" SCHEME="CELLULAR watchOS" RUN_TESTS="NO" POD_LINT="NO"
    # tvOS
    - os: osx
      env: DESTINATION="OS=11.3,name=Apple TV 4K"    SCHEME="CELLULAR tvOS" RUN_TESTS="YES" POD_LINT="NO"
    - os: osx
      env: DESTINATION="OS=10.2,name=Apple TV 1080p" SCHEME="CELLULAR tvOS" RUN_TESTS="YES" POD_LINT="NO"
    - os: osx
      env: DESTINATION="OS=9.2,name=Apple TV 1080p"  SCHEME="CELLULAR tvOS" RUN_TESTS="YES" POD_LINT="NO"

