sudo: required
dist: trusty
language: generic
osx_image: xcode9.3
branches:
    only:
        - master
        - develop

matrix:
  include:
    # Linux
    - os: linux
      env: SWIFT_VERSION=swift-4.1
    # iOS
    - os: osx
      env: DESTINATION="OS=11.3,name=iPhone X"         RUN_TESTS="YES"  POD_LINT="YES"
    - os: osx
      env: DESTINATION="OS=10.3.1,name=iPhone 7 Plus"  RUN_TESTS="YES"  POD_LINT="NO"
    - os: osx
      env: DESTINATION="OS=9.3,name=iPhone 6"          RUN_TESTS="YES"  POD_LINT="NO"
    # watchOS
    - os: osx
      env: DESTINATION="OS=4.3,name=Apple Watch - 42mm"  RUN_TESTS="NO"  POD_LINT="NO"
    - os: osx
      env: DESTINATION="OS=3.2,name=Apple Watch - 42mm"  RUN_TESTS="NO"  POD_LINT="NO"
    - os: osx
      env: DESTINATION="OS=2.2,name=Apple Watch - 42mm"  RUN_TESTS="NO"  POD_LINT="NO"
    # tvOS
    - os: osx
      env: DESTINATION="OS=11.3,name=Apple TV 4K"     RUN_TESTS="YES"  POD_LINT="NO"
    - os: osx
      env: DESTINATION="OS=10.2,name=Apple TV 1080p"  RUN_TESTS="YES"  POD_LINT="NO"
    - os: osx
      env: DESTINATION="OS=9.2,name=Apple TV 1080p"   RUN_TESTS="YES"  POD_LINT="NO"
    # macOS
    - os: osx
      env: DESTINATION="arch=x86_64"  RUN_TESTS="YES"  POD_LINT="NO"

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        eval "$(curl -sL https://swiftenv.fuller.li/install.sh)";
      else
        gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet;
      fi

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        swift build;
        swift build -c release;
        swift test;
      else
        set -o pipefail
        xcodebuild -version
        xcodebuild -showsdks
        swift package generate-xcodeproj

        PROJECT=CELLULAR.xcodeproj
        SCHEME=CELLULAR-Package

        # Build Framework in Debug and Run Tests if specified
        if [ $RUN_TESTS == "YES" ]; then
            xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
        else
            xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
        fi
        # Build Framework in Release and Run Tests if specified
        if [ $RUN_TESTS == "YES" ]; then
            xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
        else
            xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
        fi
        # Run `pod lib lint` if specified
        if [ $POD_LINT == "YES" ]; then
            pod lib lint;
        fi
      fi
