sudo: required
dist: trusty
language: generic
osx_image: xcode9.3

# Dependencies
before_install: chmod +x ./.travis/deps.sh
install: ./.travis/deps.sh

# Build Script
before_script: chmod +x ./.travis/build.sh
script: ./.travis/build.sh

# Update Code Coverage
after_success: bash <(curl -s https://codecov.io/bash)

# Notifications
notifications:
  email: false
  slack:
    rooms: #ios-informiert
      secure: xJ6An1DXP2XnLlxv87Z+SQmy1NTmkj2Ptjd1hwyX7LJARwxSHnvp4Ho/IkB4sWFQrsPGIrMlFYM+6BkidEnmcJ9EGNww3UVy8Fcr2cs4fn7SU3mJVttpIn30HC+kYA6nzIShwm0EWAOB2O1fqC8eWvy+zIcnBn/U67VpZpRJcP/pDjkRxaBIGIhyc7W5PYZGitG2oXJieDBDX2wnHTlrQQdrv9XJji+Y5Q/j0l3udvQnqGDBdR/Zvvufo3BO0bIKZMCUtTtVdfgJW++ygKl9Vsv9OvFMf86HA1JkvQTnfGXDXuBgT2mdXE30mew0KDRES3EC+FUqfANntEOSYwPzx+hRGNNwkFwQHx6wM1YKFZLrQjbLNqDvaz6WZ+i8gOT2tVJUIj4v5DQqan1oOT7vzCPTU+O/7TD0NJGuKU5KqHJy156gAtF10CJGpNZWteaGCMRyBCucnlPur7iTFWh+244aqO3+W+fhdB1VPWVzyFYcvFxulvqg7k7GI8Fa112ku9bQkWLdGx++Itk2atAJEYsh09mWgoaPo1U8JyjNG3KLNirggcd1aDgZ0bY88VBo7qJQJgdEyZuAtCnR5eESg7HruhhZ0lxDLv3jb6xMBflQeULm1GpYnBXk3fZQ4E7E+XugHgw7XCjzbq63g6dcTFLPh16gQ31L7aNnEubfQzc=
    on_success: change

# Build Matrix
matrix:
    include:
        # Linux
        - os: linux
          env: SWIFT_VERSION=swift-4.1

        # macOS
        - os: osx
          env: DESTINATION="arch=x86_64"  SCHEME="CELLULAR macOS" RUN_TESTS="YES"  POD_LINT="YES"

        # iOS
        - os: osx
          env: DESTINATION="OS=11.3,name=iPhone X"        SCHEME="CELLULAR iOS" RUN_TESTS="YES" POD_LINT="NO"
        - os: osx
          env: DESTINATION="OS=10.3.1,name=iPhone 7 Plus" SCHEME="CELLULAR iOS" RUN_TESTS="YES" POD_LINT="NO"
        - os: osx
          env: DESTINATION="OS=9.3,name=iPhone 6"         SCHEME="CELLULAR iOS" RUN_TESTS="YES" POD_LINT="NO"
        # watchOS
        - os: osx
          env: DESTINATION="OS=4.3,name=Apple Watch - 42mm" SCHEME="CELLULAR watchOS" RUN_TESTS="NO" POD_LINT="NO"
        - os: osx
          env: DESTINATION="OS=3.2,name=Apple Watch - 42mm" SCHEME="CELLULAR watchOS" RUN_TESTS="NO" POD_LINT="NO"
        - os: osx
          env: DESTINATION="OS=2.2,name=Apple Watch - 42mm" SCHEME="CELLULAR watchOS" RUN_TESTS="NO" POD_LINT="NO"
        # tvOS
        - os: osx
          env: DESTINATION="OS=11.3,name=Apple TV 4K"    SCHEME="CELLULAR tvOS" RUN_TESTS="YES" POD_LINT="NO"
        - os: osx
          env: DESTINATION="OS=10.2,name=Apple TV 1080p" SCHEME="CELLULAR tvOS" RUN_TESTS="YES" POD_LINT="NO"
        - os: osx
          env: DESTINATION="OS=9.2,name=Apple TV 1080p"  SCHEME="CELLULAR tvOS" RUN_TESTS="YES" POD_LINT="NO"

