sudo: required
dist: trusty
language: generic
osx_image: xcode9.3

# Dependencies
before_install: chmod +x ./.travis/deps.sh
install: ./.travis/deps.sh

# Build Script
before_script: chmod +x ./.travis/build.sh
script: ./.travis/build.sh

# Update Code Coverage
after_success: bash <(curl -s https://codecov.io/bash)

# Notifications
notifications:
    email: false
    slack:
        rooms:
            - secure: qZ9eD+6ryxfEjMxGrkq9kvw8NcjL4XocLiovyq3YgZz77heLs8LzXOEXYyFUinsNCAk0Jm0EudiA90rKxr5AnVQj4BPLVUjQjESi432iazuUsSYLoioMNxIV9lKyVbzwKuWveI4o/dgJ00uZ7k+DqHb1XvFogPH4wXvow9xL1d4EsdVVoKN65A7RsEgCxaqk45XHBAJmjyVa88IXFgzqg0OeXPoxdK0MCBxkLnCWWJaQ4mRliqOhPIOKEKr3pSB3gQZ0L+xKYYVhzkUPQyw88aZM+3Y6JP+dQJIsgXYQHR7Z7chm29uFutoLWph3mYrbhwOxzpWTZXxuOENztgf4OBJv1ALJqZ5JbJvkTejHYOG5OhPS8U4BproDGBM9Jt+IDTPaTN8mPcSg9It6NK/40iznFwTSlgLDfJf+NWQk6M92QllXzBIlhptiTKrCgexbUXQ83ZWG+LfVONTMtfYmHWTfDgGaPIfOeMTiLl9kpr3ZPfh8NBhhY22+j07xejq3DTRwf3CDV5ThvBz9ydQo63JdHwg0n1agzQgR7gE6wMkjMVHNmRvARLYCq3pLS/ZxP93lYXwkT9afCidcU5YOxle9l/zbfO5XDsl8kJh6MAbkEG6NvQviwsVzx+ELFImrsB0tayP+YjGkp6V1wfRVlmwSlYRxECB8jAj4LX+PYsk=
        on_success: change

# Build Matrix
matrix:
    include:
        # Linux
        - os: linux
          env: SWIFT_VERSION=swift-4.1

        # macOS
        - os: osx
          env: DESTINATION="arch=x86_64"  SCHEME="CELLULAR macOS" RUN_TESTS="NO"  POD_LINT="YES"

        # iOS
        - os: osx
          env: DESTINATION="OS=11.3,name=iPhone X"        SCHEME="CELLULAR iOS" RUN_TESTS="YES" POD_LINT="NO"
        - os: osx
          env: DESTINATION="OS=10.3.1,name=iPhone 7 Plus" SCHEME="CELLULAR iOS" RUN_TESTS="YES" POD_LINT="NO"
        - os: osx
          env: DESTINATION="OS=9.3,name=iPhone 6"         SCHEME="CELLULAR iOS" RUN_TESTS="YES" POD_LINT="NO"
        # watchOS
        - os: osx
          env: DESTINATION="OS=4.3,name=Apple Watch - 42mm" SCHEME="CELLULAR watchOS" RUN_TESTS="NO" POD_LINT="NO"
        - os: osx
          env: DESTINATION="OS=3.2,name=Apple Watch - 42mm" SCHEME="CELLULAR watchOS" RUN_TESTS="NO" POD_LINT="NO"
        - os: osx
          env: DESTINATION="OS=2.2,name=Apple Watch - 42mm" SCHEME="CELLULAR watchOS" RUN_TESTS="NO" POD_LINT="NO"
        # tvOS
        - os: osx
          env: DESTINATION="OS=11.3,name=Apple TV 4K"    SCHEME="CELLULAR tvOS" RUN_TESTS="YES" POD_LINT="NO"
        - os: osx
          env: DESTINATION="OS=10.2,name=Apple TV 1080p" SCHEME="CELLULAR tvOS" RUN_TESTS="YES" POD_LINT="NO"
        - os: osx
          env: DESTINATION="OS=9.2,name=Apple TV 1080p"  SCHEME="CELLULAR tvOS" RUN_TESTS="YES" POD_LINT="NO"

